package edu.eci.cvds.ECIBienestarGym.enums;

public enum MuscleGroup {
    CHEST, BACK, SHOULDERS, BICEPS, TRICEPS, FOREARMS, ABS, OBLIQUES, QUADRICEPS, HAMSTRINGS, CALVES, BUTTOCKS, TRAPEZOIDS, DORSAL,
}
