package edu.eci.cvds.ECIBienestarGym.enums;

public enum MuscleGroup {
    PECHO, ESPALDA, HOMBROS, BÍCEPS, TRÍCEPS, ANTEBRAZOS, ABDOMINALES, OBLICUOS, CUÁDRICEPS, ISQUIOTIBIALES, PANTORRILLAS, GLÚTEOS, TRAPECIOS, DORSALES,
}
