package edu.eci.cvds.ECIBienestarGym.enums;

public enum MuscleGroup {
    PECHO, ESPALDA, HOMBROS, BICEPS, TRICEPS, ANTEBRAZOS, ABDOMINALES, OBLICUOS, CUADRICEPS, ISQUIOTIBIALES, PANTORRILLAS, GLUTEOS, TRAPECIOS, DORSALES,
}
